### ISSUE TITLE
problem compile EspEasy

### ISSUE THREAD

**Issue by mihadongle** [letscontrolit/ESPEasyMega#2]
hallo i can´t compile the espeasy!!

Arduino: 1.6.12 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

Command:451: error: variable or field 'printDirectory' declared void

 void printDirectory(File dir, int numTabs) {

                     ^

Command:451: error: 'File' was not declared in this scope

Command:451: error: expected primary-expression before 'int'

 void printDirectory(File dir, int numTabs) {

                               ^

Networking:396: error: variable or field 'SSDP_schema' declared void

 void SSDP_schema(WiFiClient client) {

                  ^

Networking:396: error: 'WiFiClient' was not declared in this scope

_N001_Email:114: error: 'WiFiClient' was not declared in this scope

 boolean NPlugin_001_MTA(WiFiClient client, String aStr, String aWaitForPattern)

                         ^

_N001_Email:114: error: expected primary-expression before 'aStr'

 boolean NPlugin_001_MTA(WiFiClient client, String aStr, String aWaitForPattern)

                                                   ^

_N001_Email:114: error: expected primary-expression before 'aWaitForPattern'

 boolean NPlugin_001_MTA(WiFiClient client, String aStr, String aWaitForPattern)

                                                                ^

_N001_Email:114: error: expression list treated as compound expression in initializer [-fpermissive]

 boolean NPlugin_001_MTA(WiFiClient client, String aStr, String aWaitForPattern)

                                                                               ^

C:\Users\Acer\Desktop\ESPEasy-mega\espeasy\espeasy\Command.ino: In function 'void ExecuteCommand(byte, const char*)':

Command:51: error: 'RTC' was not declared in this scope

     RTC.factoryResetCounter = 0;

     ^

Command:68: error: 'Settings' was not declared in this scope

       if (Settings.NotificationEnabled[Par1 - 1] && Settings.Notification[Par1 - 1] != 0)

           ^

Command:71: error: aggregate 'EventStruct TempEvent' has incomplete type and cannot be defined

         struct EventStruct TempEvent;

                            ^

Command:73: error: 'NPlugin_id' was not declared in this scope

         if (NPlugin_id[NotificationProtocolIndex] != 0)

             ^

Command:74: error: 'NPlugin_ptr' was not declared in this scope

           NPlugin_ptr[NotificationProtocolIndex](NPLUGIN_NOTIFY, &TempEvent, message);

           ^

Command:74: error: 'NPLUGIN_NOTIFY' was not declared in this scope

           NPlugin_ptr[NotificationProtocolIndex](NPLUGIN_NOTIFY, &TempEvent, message);

                                                  ^

Command:82: error: 'RTC' was not declared in this scope

     RTC.flashDayCounter = 0;

     ^

Command:99: error: 'File' was not declared in this scope

     File root = SD.open("/");

     ^

Command:99: error: expected ';' before 'root'

     File root = SD.open("/");

          ^

Command:100: error: 'root' was not declared in this scope

     root.rewindDirectory();

     ^

Command:101: error: 'printDirectory' was not declared in this scope

     printDirectory(root, 0);

                           ^

Command:112: error: 'SD' was not declared in this scope

     SD.remove((char*)fname.c_str());

     ^

Command:117: error: 'lowestRAM' was not declared in this scope

     Serial.print(lowestRAM);

                  ^

Command:119: error: 'lowestRAMid' was not declared in this scope

     Serial.println(lowestRAMid);

                    ^

Command:132: error: 'loopCounterLast' was not declared in this scope

     Serial.print(100 - (100 * loopCounterLast / loopCounterMax));

                               ^

Command:132: error: 'loopCounterMax' was not declared in this scope

     Serial.print(100 - (100 * loopCounterLast / loopCounterMax));

                                                 ^

Command:150: error: 'SecuritySettings' was not declared in this scope

     Serial.println(sizeof(SecuritySettings));

                           ^

Command:152: error: 'Settings' was not declared in this scope

     Serial.println(sizeof(Settings));

                           ^

Command:154: error: 'ExtraTaskSettings' was not declared in this scope

     Serial.println(sizeof(ExtraTaskSettings));

                           ^

Command:156: error: 'Device' was not declared in this scope

     Serial.println(sizeof(Device));

                           ^

Command:168: error: 'Wire' was not declared in this scope

     Wire.beginTransmission(Par1);  // address

     ^

Command:177: error: 'Wire' was not declared in this scope

     Wire.beginTransmission(Par1);  // address

     ^

Command:193: error: 'Settings' was not declared in this scope

     Settings.Build = Par1;

     ^

Command:200: error: 'Settings' was not declared in this scope

     Settings.deepSleep = 0;

     ^

Command:222: error: 'UserVar' was not declared in this scope

       UserVar[(VARS_PER_TASK * (Par1 - 1)) + Par2 - 1] = result;

       ^

Command:222: error: 'VARS_PER_TASK' was not declared in this scope

       UserVar[(VARS_PER_TASK * (Par1 - 1)) + Par2 - 1] = result;

                ^

Command:235: error: 'RulesTimer' was not declared in this scope

     RulesTimer[Par1 - 1] = millis() + (1000 * Par2);

     ^

Command:248: error: 'Settings' was not declared in this scope

       Settings.UseRules = true;

       ^

Command:250: error: 'Settings' was not declared in this scope

       Settings.UseRules = false;

       ^

Command:259: error: 'Settings' was not declared in this scope

     if (Settings.UseRules)

         ^

Command:286: error: 'MQTTclient' was not declared in this scope

       MQTTclient.publish(topic.c_str(), value.c_str(), Settings.MQTTRetainFlag);

       ^

Command:286: error: 'Settings' was not declared in this scope

       MQTTclient.publish(topic.c_str(), value.c_str(), Settings.MQTTRetainFlag);

                                                        ^

Command:300: error: 'IPAddress' was not declared in this scope

     IPAddress UDP_IP(ipaddress[0], ipaddress[1], ipaddress[2], ipaddress[3]);

     ^

Command:300: error: expected ';' before 'UDP_IP'

     IPAddress UDP_IP(ipaddress[0], ipaddress[1], ipaddress[2], ipaddress[3]);

               ^

Command:301: error: 'portUDP' was not declared in this scope

     portUDP.beginPacket(UDP_IP, port.toInt());

     ^

Command:301: error: 'UDP_IP' was not declared in this scope

     portUDP.beginPacket(UDP_IP, port.toInt());

                         ^

Command:314: error: 'WiFiClient' was not declared in this scope

     WiFiClient client;

     ^

Command:314: error: expected ';' before 'client'

     WiFiClient client;

                ^

Command:315: error: 'client' was not declared in this scope

     if (client.connect(host.c_str(), port.toInt()))

         ^

Command:328: error: 'LOG_LEVEL_DEBUG' was not declared in this scope

           addLog(LOG_LEVEL_DEBUG, line);

                  ^

Command:343: error: 'SecuritySettings' was not declared in this scope

     strcpy(SecuritySettings.WifiSSID, Line + 9);

            ^

Command:349: error: 'SecuritySettings' was not declared in this scope

     strcpy(SecuritySettings.WifiKey, Line + 8);

            ^

Command:387: error: 'WiFi' was not declared in this scope

     WiFi.persistent(true); // use SDK storage of SSID/WPA parameters

     ^

Command:413: error: 'Settings' was not declared in this scope

     Settings.SerialLogLevel = Par1;

     ^

Command:420: error: 'Settings' was not declared in this scope

       if (!str2ip(TmpStr1, Settings.IP))

                            ^

Command:431: error: 'IPAddress' was not declared in this scope

     IPAddress ip = WiFi.localIP();

     ^

Command:431: error: expected ';' before 'ip'

     IPAddress ip = WiFi.localIP();

               ^

Command:432: error: 'ip' was not declared in this scope

     sprintf_P(str, PSTR("%u.%u.%u.%u"), ip[0], ip[1], ip[2], ip[3]);

                                         ^

Command:434: error: 'BUILD' was not declared in this scope

     Serial.print(F("  Build         : ")); Serial.println((int)BUILD);

                                                                ^

Command:435: error: 'Settings' was not declared in this scope

     Serial.print(F("  Unit          : ")); Serial.println((int)Settings.Unit);

                                                                ^

Command:436: error: 'SecuritySettings' was not declared in this scope

     Serial.print(F("  WifiSSID      : ")); Serial.println(SecuritySettings.WifiSSID);

                                                           ^

C:\Users\Acer\Desktop\ESPEasy-mega\espeasy\espeasy\Command.ino: At global scope:

Command:451: error: variable or field 'printDirectory' declared void

 void printDirectory(File dir, int numTabs) {

                     ^

Command:451: error: 'File' was not declared in this scope

Command:451: error: expected primary-expression before 'int'

 void printDirectory(File dir, int numTabs) {

                               ^

In file included from c:\users\acer\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\typeinfo:34:0,

                 from c:\users\acer\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\functional:53,

                 from C:\Users\Acer\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/ESP8266WiFiGeneric.h:27,

                 from C:\Users\Acer\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/ESP8266WiFiSTA.h:28,

                 from C:\Users\Acer\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\ESP8266WiFi\src/ESP8266WiFi.h:34,

                 from C:\Users\Acer\Desktop\ESPEasy-mega\espeasy\espeasy\ESPEasy.ino:247:

c:\users\acer\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\1.20.0-26-gb404fb9-2\xtensa-lx106-elf\include\c++\4.8.2\exception:35:37: error: expected declaration before end of line

 #pragma GCC visibility push(default)

                                     ^

Mehrere Bibliotheken wurden für "SD.h" gefunden
 Benutzt: C:\Users\Acer\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\SD
 Nicht benutzt: C:\Users\Acer\Desktop\arduino-1.6.12\libraries\SD
Mehrere Bibliotheken wurden für "Servo.h" gefunden
 Benutzt: C:\Users\Acer\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\Servo
 Nicht benutzt: C:\Users\Acer\Desktop\arduino-1.6.12\libraries\Servo
exit status 1
variable or field 'printDirectory' declared void

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by beicnet** [comment]
@mihadongle This source is not for ESP8266 platform, it's for the Arduino Mega board!

**Comment by ayasystems** [comment]
I have the same problem. https://github.com/letscontrolit/ESPEasy seems has the mega code

**Comment by beicnet** [comment]
Download from here: [https://github.com/letscontrolit/ESPEasy/releases](url)
